name: avo_ai_diet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Animation
  lottie: ^3.3.1
  percent_indicator: ^4.2.5
  fluttertoast: ^8.2.12


  # Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Core
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  flutter_markdown: ^0.7.7
  font_awesome_flutter: ^10.8.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  flutter_svg: ^2.1.0
  xml: ^6.5.0
  connectivity_plus: ^6.1.4


  # Firebase
  firebase_core: ^3.13.1
  firebase_ai: ^2.0.0
  firebase_app_check: ^0.3.2+6
  firebase_remote_config: ^5.4.4
  firebase_analytics: ^11.4.6

  # Navigation
  go_router: ^15.1.1

  # Private Key
  flutter_dotenv: ^5.2.1

  # Service
  google_generative_ai: ^0.4.6

  # State Managment
  flutter_hooks: ^0.21.2
  flutter_bloc: ^9.1.1
  device_info_plus: ^11.4.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15  
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/png/
    - assets/json/
    - assets/svg/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
  
