name: avo_ai_diet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Animation
  lottie: ^3.2.0

  # Core
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  get_it: ^7.6.0
  injectable: ^2.1.0

  # Navigation
  go_router: ^14.6.2

  # Private Key
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.3

  # Service
  google_generative_ai: ^0.4.6

  # State Managment
  flutter_hooks: ^0.20.5
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.8  
  injectable_generator: ^2.1.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/png/
    - assets/json/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
  
